version: "3.5"

services:
  jenkins:
    build: .
    restart: always
    container_name: jenkins
    image: webnsurf-jenkins
    ports:
      - 8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - "$DOCKER_PATH:$DOCKER_PATH"
      - "$DOCKER_COMPOSE_PATH:$DOCKER_COMPOSE_PATH"
    labels:
      traefik.enable: true
      traefik.http.routers.jenkins-redirect.rule: Host(`jenkins.webnsurf.com`)
      traefik.http.routers.jenkins-redirect.entrypoints: web
      traefik.http.routers.jenkins-redirect.middlewares: https-redirect@file

      traefik.http.routers.jenkins-frontend.rule: Host(`jenkins.webnsurf.com`)
      traefik.http.routers.jenkins-frontend.entrypoints: websecure
      traefik.http.routers.jenkins-frontend.tls: true

networks:
  default:
    external:
      name: webnsurf_network
